<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_State or Province_stateProvince</name>
   <tag></tag>
   <elementGuidId>a83f3df0-4eaf-4022-b6bc-efda270cef44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stateProvince']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#stateProvince</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;State or Province&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d874028c-6b69-4460-9189-dfbc19a2e580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stateProvince</value>
      <webElementGuid>f8256d31-9f38-4a63-b55d-d0e352c0a75e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>State or Province</value>
      <webElementGuid>54a9cac2-e4ad-4018-8a4f-94151ede858d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stateProvince&quot;)</value>
      <webElementGuid>72b8b765-39ae-444d-ac59-4ef72fac671c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stateProvince']</value>
      <webElementGuid>77787124-9317-456f-94c9-5b20a3197b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-contact']/p[6]/input[2]</value>
      <webElementGuid>c32531e6-b562-4ffd-b851-e613b0d154b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/input[2]</value>
      <webElementGuid>8ba3c101-3ab7-4bb6-9ec4-17aed123c19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'stateProvince' and @placeholder = 'State or Province']</value>
      <webElementGuid>a08f41a2-7138-4581-9ec8-ef700f2c5351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
