<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_birthdate</name>
   <tag></tag>
   <elementGuidId>0b4f65c7-1c27-4d12-9730-b62f2d1c3e9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthdate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#birthdate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;yyyy-MM-dd&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67e73809-d5e8-41d6-91e3-9278cde46ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthdate</value>
      <webElementGuid>05365034-11a2-4eb9-acd9-2f41aa8cbd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>yyyy-MM-dd</value>
      <webElementGuid>07e0d650-613d-4847-abfe-8b803f85f801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;birthdate&quot;)</value>
      <webElementGuid>99309324-a13f-409a-8a1f-9ea557507fb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthdate']</value>
      <webElementGuid>1bcba70d-a928-475e-8705-9a7af5877566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-contact']/p[2]/input</value>
      <webElementGuid>b87ea099-6c3b-48e6-8ab6-465fac908d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/input</value>
      <webElementGuid>56f422ff-d0c6-44eb-b3d4-57b6005b14f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'birthdate' and @placeholder = 'yyyy-MM-dd']</value>
      <webElementGuid>4f57be42-4b7f-4d17-9d51-9ba6fbb5e042</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
